name: Backend image Build and Push

on:
  push:
    branches: [main, dev]

jobs:
  prod:
    name: PROD ENV
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker image
        run: |
          docker build -t priyankatuladhar/backend-git-action:stable -t priyankatuladhar/backend-git-action:$(git rev-parse --short "$GITHUB_SHA") .
          docker images
          docker push priyankatuladhar/backend-git-action:stable
          docker push priyankatuladhar/backend-git-action:$(git rev-parse --short "$GITHUB_SHA")

     # - name: Increase package.json version
      #  uses: stefanzweifel/npm-version-action@v4

      - name: Commit version increase
        run: |
          npm version patch
          git add package.json
          git commit -m "Increase package.json version"
          git push --follow-tags
  dev:
    name: DEV ENV
    runs-on: self-hosted
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker image
        run: |
          docker build -t priyankatuladhar/backend-git-action:dev -t priyankatuladhar/backend-git-action:$(git rev-parse --short "$GITHUB_SHA") .
          docker images
          docker push priyankatuladhar/backend-git-action:dev
          docker push priyankatuladhar/backend-git-action:$(git rev-parse --short "$GITHUB_SHA")
